version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Building...
artifacts:
  files:
      - index.html
      - assets/**/*
      - speakers/*
  name: website
